### ISSUE TITLE
Convert coffee to js

### ISSUE THREAD

**Issue by ysmood** [ysmood/nobone-sync#10]

**Comment by dracupid** [comment]
Why coffee is deprecated？

**Comment by ysmood** [comment]
Because of ES7, I found coffee's reaction to new js feature is slowing down. ES7 is much powerful than coffee.

**Comment by dracupid** [comment]
Yes, ES7 even ES6 is good enough except brackets. Coffeescript is losing energy.

**Comment by ysmood** [comment]
No, ES6 can work without brackets

``` js
// js
foo = a => b => a + b
```

It's even less code than coffee, coffee has to write braces

``` coffee
# coffee
foo = (a) -> (b) -> a + b
```

**Comment by ysmood** [comment]
3fefb908ca2955256285e90fec7450f6ef9ba629
