### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by megidmegid** [ysmood/nobone-sync#12]
Nobone-sync immediately stop after start in my server. It didn't show me any error message.
It just show me:

[ayaka@sadfsa bin]$ sudo nobone-sync 
[2018-05-10 16:38:35] No config specified, use default. 0ms
[2018-05-10 16:38:35] Watched: 0 9ms
[ayaka@sadfsa bin]$ 
[ayaka@sadfsa bin]$ 

If I start it as a daemon process, it also immediately exit without any error message.
What happend? What's wrong? Can you help me?

**Comment by ysmood** [comment]
because no file to watch, it will exit

**Comment by megidmegid** [comment]
thanks,  nobone-sync is still a good tool. I prefer it than sftp of sublime text 3.
