### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by polandeme** [ysmood/nobone-sync#7]
when nobone-sync cofig.coffee it's show 

```
 Error: connect ECONNREFUSED
  at exports._errnoException (util.js:746:11)
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
```

how to resolve it 
thx

**Comment by ysmood** [comment]
There are many possibilities, such as, your nobone-sync server is down, you are behind a firewall, you don't have the access to the nobone-sync server, you use the wrong ip or port settings.

**Comment by polandeme** [comment]
@ysmood  thx, it's works, because my nobone-sync server is down.

**Comment by polandeme** [comment]
@ysmood if I use username & password connect the server ,how can i do? THX

**Comment by ysmood** [comment]
There's no user concept for now. You can only use a password to secure the connection.

**Comment by polandeme** [comment]
But I want connect a server which need 'work' as user and must use password. so i can't use it if so?

**Comment by ysmood** [comment]
In brief, yes, you can't. This tool is designed for some limited simple cases. Don't expect too much from it.

**Comment by polandeme** [comment]
all right, But thx
